# Exercise   

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,
    
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [2]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
import numpy as np

In [3]:
iris = load_iris()

In [4]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

D:\JupyterNotebook\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [5]:
np.mean(l_scores)

np.float64(0.9733333333333334)

In [7]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [8]:
np.mean(dt_scores)

np.float64(0.9600000000000002)

In [25]:
rf_scores = cross_val_score(RandomForestClassifier(n_estimators=100), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [26]:
np.mean(rf_scores)

np.float64(0.9666666666666668)

In [11]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [12]:
np.mean(svm_scores)

np.float64(0.9666666666666666)